layout_spectrum: 0.5698174
color:
  saturation: 0.7887471
  lightness: 0.2559954
  brandStrength: 0.5649299
  brandColors:
    - '#DEDFD9'
    - '#160E0C'
    - '#A36E53'
    - '#654131'
    - '#02389A'
  rhythmicContrast: 0.293728
typography_spectrum: 0.7019334
name: Skincare
